version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - ./migrations:/migrations
        - ./pgmigrate:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
