GRANT ALL ON DATABASE library TO postgres;
create schema if not exists mklib;
create table if not exists mklib.customer(
    id bigint generated by default as identity primary key,
    full_name varchar not null,
    additional_info jsonb
);
create table if not exists mklib.genre(
    id integer primary key,
    name varchar,
    age_restrictions integer,
    description text
);
--Вот так вот
