create schema if not exists refer;
create table refer.country(
    id integer primary key generated by default as identity,
    name varchar not null,
    short_name varchar(5) not null,
    region varchar not null
);
create table if not exists mklib.author(
    id bigint primary key generated by default as identity,
    full_name varchar not null,
    country integer references refer.country(id),
    birth_date date not null default now()
);

create table if not exists mklib.poem(
    id bigint primary key generated by default as identity,
    name varchar not null,
    id_genre integer references mklib.genre(id),
    number_of_pages integer not null,
    id_author integer references mklib.author(id),
    date_create date not null default now(),
    description text
);
